name: Bikes Test

on:
  workflow_dispatch:
  push:
    branches:
      - "dev/**"
    paths:
      - "env/**"
      - "src/**"

permissions:
  id-token: write
  contents: read

env:
  TEMPLATE_FILE: "./env/main.bicep"
  PARAMETER_TEST_FILE: "./env/main.parameters.test.json"

jobs:
    build-infra:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build
          run: az bicep build --file ${{ env.TEMPLATE_FILE }}

        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: infra
            path: ./env/
    
    build-site:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Setup EF
              run: |
                dotnet tool install --global dotnet-ef
                dotnet tool restore

            - name: Restore
              run: |
                dotnet restore ./src/cicloso.bikes.sln

            - name: Build
              run: |
                dotnet build ./src/cicloso.bikes.sln \
                --no-restore \
                --configuration Release

            # - name: Test
            #   run: |
            #     dotnet test --no-build --configuration Release \
            #     --collect:"XPlat Code Coverage"

            # - name: Publish test results
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: test-results
            #     path: |
            #       **/TestResults/**

            - name: Scan
              uses: SonarSource/sonarqube-scan-action@v7.0.0 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                projectBaseDir: ./src
                args: >
                    -Dsonar.organization=daleospina-gh
                    -Dsonar.projectName=bikes
                    -Dsonar.projectKey=bikes
                    -Dsonar.sources=.
                    -Dsonar.verbose=true

            - name: Log connection string length
              run: |
                echo "Len: ${#BikesContext}"
              env:
                BikesContext: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

            - name: Bundle database 
              run: | 
                dotnet ef migrations bundle \
                --project ./src/cicloso.bikes.core/cicloso.bikes.core.csproj \
                -r linux-x64
              env:
                BikesContext: ${{ vars.AZURE_SQL_CONNECTION_STRING }}

            - name: Publish api
              run: |
                dotnet publish ./src/cicloso.bikes.api/cicloso.bikes.api.csproj \
                -c Release \
                -o publish/api

            - name: Publish app
              run: |
                dotnet publish ./src/cicloso.bikes.app/cicloso.bikes.app.csproj \
                -c Release \
                -o publish/app

            - name: Zip site
              run: |
                cd publish
                zip -r api.zip api
                zip -r app.zip app

            - name: Upload database
              uses: actions/upload-artifact@v4
              with:
                name: database
                path: ./efbundle

            - name: Upload site
              uses: actions/upload-artifact@v4
              with:
                name: site
                path: publish/*.zip

    deploy-infra:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        environment: test
        needs: [build-infra, build-site]
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Sign in to azure
          uses: azure/login@v3
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Create resource group
          uses: azure/CLI@v2
          with:
            inlineScript: |
                az group create --name  ${{ vars.AZURE_RESOURCEGROUP_NAME }} --location ${{ vars.AZURE_LOCATION_NAME }}     
        
        - name: Validate bicep
          uses: azure/bicep-deploy@v2
          with:
            type: deployment
            operation: validate
            scope: resourceGroup
            name: ${{ github.run_number }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
            template-file: ${{ env.TEMPLATE_FILE }}
            parameters-file: ${{ env.PARAMETER_TEST_FILE }}

        - name: Deploy to azure
          id: deploy
          uses: azure/bicep-deploy@v2
          with:
            type: deployment
            operation: create
            scope: resourceGroup
            name: ${{ github.run_number }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
            template-file: ${{ env.TEMPLATE_FILE }}
            parameters-file: ${{ env.PARAMETER_TEST_FILE }}

        outputs:
            appHostName: ${{ steps.deploy.outputs.appHostName }}
            apiHostName: ${{ steps.deploy.outputs.apiHostName }}
            sqlServerName: ${{ steps.deploy.outputs.sqlServerName }}
            sqlDatabaseName: ${{ steps.deploy.outputs.sqlDatabaseName }}
    
    deploy-site:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs: deploy-infra
        environment: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: site
                path: artifacts

            - name: Log in with Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Migrate database 
              shell: bash 
              run: |  
                chmod +x ./artifacts/efbundle/efbundle 
                ./artifacts/efbundle/efbundle --connection "${{ vars.AZURE_SQL_CONNECTION_STRING }}"

            - name: Deploy api
              uses: azure/webapps-deploy@v3
              with:
                resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
                app-name: ${{ vars.AZURE_API_APPSERVICE_NAME }}
                package: artifacts/api.zip

            - name: Verify api
              run: |
                az webapp show \
                    --resource-group ${{ vars.AZURE_RESOURCEGROUP_NAME }} \
                    --name ${{ vars.AZURE_API_APPSERVICE_NAME }} \
                    --query state
            
            - name: Deploy app
              uses: azure/webapps-deploy@v3
              with:
                resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
                app-name: ${{ vars.AZURE_APP_APPSERVICE_NAME }}
                package: artifacts/app.zip

            - name: Verify app
              run: |
                az webapp show \
                    --resource-group ${{ vars.AZURE_RESOURCEGROUP_NAME }} \
                    --name ${{ vars.AZURE_APP_APPSERVICE_NAME }} \
                    --query state

    validate-perfomance:
        runs-on: ubuntu-latest
        needs: deploy-site
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Lighthouse scan
          uses: treosh/lighthouse-ci-action@v12
          with:
            urls: |
                https://app-bikes-app-test-gwjeyl.azurewebsites.net/
                https://app-bikes-app-test-gwjeyl.azurewebsites.net/Customer
                https://app-bikes-app-test-gwjeyl.azurewebsites.net/City
                https://app-bikes-app-test-gwjeyl.azurewebsites.net/Theater
            uploadArtifacts: true # save results as an action artifacts
            temporaryPublicStorage: true # upload lighthouse report to the temporary storage
    
    validate-security:
        runs-on: ubuntu-latest
        needs: deploy-site
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: ZAP scan
          uses: zaproxy/action-full-scan@v0.13.0
          with:
            target: 'https://app-bikes-app-test-gwjeyl.azurewebsites.net/'
            allow_issue_writing: false