name: Bikes Test

on:
  workflow_dispatch:
  push:
    branches:
      - "dev/**"
    paths:
      - "env/**"
      - "src/**"

permissions:
  id-token: write
  contents: read

jobs:
    build-infra:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
          TEMPLATE_FILE: "./env/main.bicep"
          
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build
          run: az bicep build --file ${{ env.TEMPLATE_FILE }}

        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: infra
            path: ./env/
    
    build-solution:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
          SOLUTION_FILE: "./src/cicloso.bikes.sln"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Setup EF
              run: |
                dotnet tool install --global dotnet-ef
                dotnet tool restore

            - name: Restore
              run: |
                dotnet restore ${{ env.SOLUTION_FILE }}

            - name: Build
              run: |
                dotnet build ${{ env.SOLUTION_FILE }} \
                --no-restore \
                --configuration Release

            - name: Scan
              uses: SonarSource/sonarqube-scan-action@v7.0.0 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                projectBaseDir: ./src
                args: >
                    -Dsonar.organization=daleospina-gh
                    -Dsonar.projectName=bikes
                    -Dsonar.projectKey=bikes
                    -Dsonar.sources=.
                    -Dsonar.verbose=true

            - name: Bundle database 
              run: | 
                dotnet ef migrations bundle \
                --project ./src/cicloso.bikes.core/cicloso.bikes.core.csproj \
                -r linux-x64
              env:
                BikesContext: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

            - name: Publish api
              run: |
                dotnet publish ./src/cicloso.bikes.api/cicloso.bikes.api.csproj \
                -c Release \
                -o publish/api

            - name: Publish app
              run: |
                dotnet publish ./src/cicloso.bikes.app/cicloso.bikes.app.csproj \
                -c Release \
                -o publish/app

            - name: Zip api
              run: |
                cd publish/api
                zip -r ../api.zip .

            - name: Zip app
              run: |
                cd publish/app
                zip -r ../app.zip .

            - name: Upload database
              uses: actions/upload-artifact@v4
              with:
                name: database
                path: ./efbundle

            - name: Upload site
              uses: actions/upload-artifact@v4
              with:
                name: site
                path: publish/*.zip

    deploy-infra:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        environment: test
        needs: [build-infra, build-solution]
        env:
            TEMPLATE_FILE: "./artifacts/main.bicep"
            PARAMETER_TEST_FILE: "./artifacts/main.parameters.test.json"
        
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: infra
            path: artifacts
        
        - name: Display structure of downloaded files
          run: ls -R

        - name: Sign in to azure
          uses: azure/login@v3
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Create resource group
          uses: azure/CLI@v2
          with:
            inlineScript: |
                az group create --name  ${{ vars.AZURE_RESOURCEGROUP_NAME }} --location ${{ vars.AZURE_LOCATION_NAME }}     
        
        - name: Validate bicep
          uses: azure/bicep-deploy@v2
          with:
            type: deployment
            operation: validate
            scope: resourceGroup
            name: ${{ github.run_number }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
            template-file: ${{ env.TEMPLATE_FILE }}
            parameters-file: ${{ env.PARAMETER_TEST_FILE }}

        - name: Deploy to azure
          id: deploy
          uses: azure/bicep-deploy@v2
          with:
            type: deployment
            operation: create
            scope: resourceGroup
            name: ${{ github.run_number }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
            template-file: ${{ env.TEMPLATE_FILE }}
            parameters-file: ${{ env.PARAMETER_TEST_FILE }}

        outputs:
            appHostName: ${{ steps.deploy.outputs.appHostName }}
            apiHostName: ${{ steps.deploy.outputs.apiHostName }}
            sqlServerFQDN: ${{ steps.deploy.outputs.sqlServerFQDN }}
            sqlServerName: ${{ steps.deploy.outputs.sqlServerName }}
            sqlDatabaseName: ${{ steps.deploy.outputs.sqlDatabaseName }}
            storageName: ${{ steps.deploy.outputs.storageName }}
            storageKey: ${{ steps.deploy.outputs.storageKey }}
            storageEnvironment: ${{ steps.deploy.outputs.storageEnvironment }}
            storageFileShareName: ${{ steps.deploy.outputs.storageFileShareName }}

    deploy-solution:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        needs: deploy-infra
        environment: test

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                path: artifacts

            - name: Display structure of downloaded files
              run: ls -R

            - name: Log in with Azure
              uses: azure/login@v3
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Open database firewall for runner
              run: |
                az sql server firewall-rule create \
                  --resource-group ${{ vars.AZURE_RESOURCEGROUP_NAME }} \
                  --server ${{ needs.deploy-infra.outputs.sqlServerName }} \
                  --name github-runner \
                  --start-ip-address 0.0.0.0 \
                  --end-ip-address 0.0.0.0

            - name: Migrate database 
              shell: bash 
              run: |  
                chmod +x ./artifacts/database/efbundle 
                ./artifacts/database/efbundle --connection "$CONN"
              env:
                CONN: ${{ vars.AZURE_SQL_CONNECTION_STRING }}

            - name: Create script for database user
              run: |
                cat <<EOF > inline_script.sql
                
                DECLARE @sqlCommand VARCHAR(4096);
                DECLARE @databaseUserName VARCHAR(4096) = '$(databaseUserName)';
                DECLARE @databaseUserPassword VARCHAR(4096) = '$(databaseUserPassword)';
                
                IF NOT EXISTS (SELECT TOP 1 * FROM sys.database_principals WHERE NAME = @databaseUserName)
                BEGIN
                  SET @sqlCommand = 'CREATE USER [' + @databaseUserName + '] WITH PASSWORD = ''' + @databaseUserPassword + ''''
                  PRINT @sqlCommand
                  EXEC (@sqlCommand)
                
                  SET @sqlCommand = 'GRANT EXEC TO [' + @databaseUserName + ']';
                  PRINT @sqlCommand
                  EXEC (@sqlCommand)
                    
                  SET @sqlCommand = 'EXECUTE sp_addrolemember db_datawriter, ''' + @databaseUserName + '''';
                  PRINT @sqlCommand
                  EXEC (@sqlCommand)
                
                  SET @sqlCommand = 'EXECUTE sp_addrolemember db_datareader, ''' + @databaseUserName + '''';
                  PRINT @sqlCommand
                  EXEC (@sqlCommand)
                END
                EOF

            - name: Run script for database user
              uses: azure/sql-action@v2
              with:
                connection-string: ${{ vars.AZURE_SQL_CONNECTION_STRING }}
                path: './inline_script.sql'
                action: 'Run'
                arguments: '-v databaseUserName=$(USER) -v databaseUserPassword=$(PASS)'
              env:
                USER: ${{ vars.SQL_DATABASE_CONTRIBUTOR_USER }}
                PASS: ${{ vars.SQL_DATABASE_CONTRIBUTOR_PASSWORD }}
            
            - name: Setup connection string
              run: |
                    echo "SQL_CONNECTION_STRING=Server=tcp:${{ needs.deploy-infra.outputs.sqlServerFQDN }},1433;Initial Catalog=${{ needs.deploy-infra.outputs.sqlDatabaseName }};Persist Security Info=False;User ID=${{ env.USER }};Password=${{ env.PASS }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" >> $GITHUB_ENV
                    echo "STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=${{ needs.deploy-infra.outputs.storageName }};AccountKey=${{ needs.deploy-infra.outputs.storageKey }};EndpointSuffix=${{ needs.deploy-infra.outputs.storageEnvironment }}'" >> $GITHUB_ENV
                    echo "STORAGE_FILE_SERVICE_URL=https://${{ needs.deploy-infra.outputs.storageName }}.file.${{ needs.deploy-infra.outputs.storageEnvironment }}" >> $GITHUB_ENV
              env:
                USER: ${{ vars.SQL_DATABASE_CONTRIBUTOR_USER }}
                PASS: ${{ vars.SQL_DATABASE_CONTRIBUTOR_PASSWORD }}

            - name: Deploy api
              uses: azure/webapps-deploy@v3
              with:
                resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
                app-name: ${{ needs.deploy-infra.outputs.apiHostName }}
                package: ./artifacts/site/api.zip

            - name: Update api service settings
              uses: Azure/appservice-settings@v1
              with:
                app-name: ${{ needs.deploy-infra.outputs.apiHostName }}
                app-settings-json: |
                                  [
                                    { 
                                      "name": "AzureStorage__fileShareUrl", 
                                      "value": "${{ env.STORAGE_FILE_SERVICE_URL }}", 
                                      "slotSetting": false 
                                    },
                                    { 
                                      "name": "AzureStorage__fileShareName", 
                                      "value": "${{ needs.deploy-infra.outputs.storageFileShareName }}", 
                                      "slotSetting": false 
                                    }
                                  ]
                connection-strings-json: |
                                        [
                                          { 
                                            "name": "BikesContext", 
                                            "value": "${{ env.SQL_CONNECTION_STRING }}",
                                            "type": "SQLAzure",
                                            "slotSetting": false 
                                          },
                                          {
                                            "name": "bikeStorage", 
                                            "value": "${{ env.STORAGE_CONNECTION_STRING }}",
                                            "type": "Custom",
                                            "slotSetting": false 
                                          }
                                        ]
            
            - name: Deploy app
              uses: azure/webapps-deploy@v3
              with:
                resource-group-name: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
                app-name: ${{ needs.deploy-infra.outputs.appHostName }}
                package: ./artifacts/site/app.zip

            - name: Update app service settings
              uses: Azure/appservice-settings@v1
              with:
                app-name: ${{ needs.deploy-infra.outputs.appHostName }}
                app-settings-json: |
                                  [
                                    { 
                                      "name": "AzureStorage__fileShareUrl", 
                                      "value": "${{ env.STORAGE_FILE_SERVICE_URL }}", 
                                      "slotSetting": false 
                                    },
                                    { 
                                      "name": "AzureStorage__fileShareName", 
                                      "value": "${{ needs.deploy-infra.outputs.storageFileShareName }}", 
                                      "slotSetting": false 
                                    }
                                  ]
                connection-strings-json: |
                                        [
                                          { 
                                            "name": "BikesContext", 
                                            "value": "${{ env.SQL_CONNECTION_STRING }}",
                                            "type": "SQLAzure",
                                            "slotSetting": false 
                                          },
                                          {
                                            "name": "bikeStorage", 
                                            "value": "${{ env.STORAGE_CONNECTION_STRING }}",
                                            "type": "Custom",
                                            "slotSetting": false 
                                          }
                                        ]

            - name: Close database firewall for runner
              if: always()
              run: |
                az sql server firewall-rule delete \
                  --resource-group ${{ vars.AZURE_RESOURCEGROUP_NAME }} \
                  --server ${{ needs.deploy-infra.outputs.sqlServerName }} \
                  --name github-runner
        
        outputs:
          webApiURL: ${{ format('https://{0}.azurewebsites.net', needs.deploy-infra.outputs.apiHostName) }}
          webAppURL: ${{ format('https://{0}.azurewebsites.net', needs.deploy-infra.outputs.appHostName) }}

    scan-solution:
        runs-on: ubuntu-latest
        needs: deploy-solution
        steps:
        
        - name: Smoke test
          run: |
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ needs.deploy-solution.outputs.webAppURL }})
            if [ $STATUS -ne 200 ]; then
              echo "Smoke test failed with status $STATUS"
              exit 1
            fi
            echo "Smoke test passed!"  
          
        - name: Lighthouse scan
          uses: treosh/lighthouse-ci-action@v12
          with:
            urls: |
                ${{ needs.deploy-solution.outputs.webAppURL }}
                ${{ needs.deploy-solution.outputs.webAppURL }}/Bikes
            uploadArtifacts: true # save results as an action artifacts
            temporaryPublicStorage: true # upload lighthouse report to the temporary storage

        - name: ZAP scan
          uses: zaproxy/action-baseline@v0.15.0
          with:
            target: ${{ needs.deploy-solution.outputs.webAppURL }}
            allow_issue_writing: false

        